POST http://localhost:8080/unsubscribe
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json
data: jsonString

{
"email": "test",
"password": "test",
"subjectName": "Mathe I"
}

###